### ISSUE TITLE
WooCommerce Description overwrites Short Description on sync

### ISSUE THREAD

**Issue by ServusNL** [libracore/WooCommerceConnector#40]
Hey,

It seems that the WooCommerceConnector overwrites the Short Description in WordPress by the Description. So after sync the information on my webshop changes.

WooCommerceConnector log shows all succes.

Edit (21:25): After looking at my product details in ERPNext, and checking the form settings, it turns out there is no "woocommerce_short_description" field. 

Regards,
Sander

**Comment by FreezeS** [comment]
Hi Sander,

This problem is because the sync module checks the same 3 fields when putting both the description and short description: woocommerce_description, web_long_description (description on website), description (of the item).

I made a quick fix that changes the priority for the short description to: description, web_long_description, woocommerce_description.

This way you can put the long description in woocommerce_description and the short description in the item description field.

Check later to see if the pull request is merged: https://github.com/libracore/WooCommerceConnector/pull/42
